version: '3.3'

services:

    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=latest
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=production
                - YARN=false
        volumes:
            - ../:/opt/app
        entrypoint: run-nodock "node index.js"
        tty: true

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        expose:
            - "3306"

    postgresql:
        build:
            context: ./postgresql
            args:
                - POSTGRES_USER=default_user
                - POSTGRES_PASSWORD=secret
                - POSTGRES_DB=default_db
        volumes:
            - ./data/postgresql/:/var/lib/postgresql
        expose:
            - "5432"

    mongo:
        build: ./mongo
        expose:
            - "27017"
        volumes:
            - ./data/mongo/:/var/lib/mongodb

    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true

    apache:
        build:
            context: ./apache
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes:
            - ./data/logs/apache/:/usr/local/apache2/logs
            - ./certbot/certs/:/var/certs
        ports:
            - "80:80"
            - "443:443"
        tty: true

    certbot:
        build:
            context: ./certbot
        links:
            - apache
            - nginx
        volumes:
          - ./certbot/letsencrypt/:/var/www/letsencrypt
          - ./certbot/certs/:/var/certs

    rabbitmq:
        build:
            context: ./rabbitmq
            args:
                - MANAGEMENT=false
                - FEDERATION=false
                - RABBITMQ_DEFAULT_USER=guest
                - RABBITMQ_DEFAULT_PASS=guest
        expose:
            - "5672"

    workspace:
        build:
            context: ./workspace
            args:
                - NODE_VERSION=latest
                - TZ=UTC
        links:
            - nginx
        volumes:
            - ../:/opt/app

    memcached:
        build:
            context: ./memcached
        expose:
            - "11211"

    redis:
        build:
            context: ./redis
        expose:
            - "6379"
        volumes:
            - ./data/redis:/data

    rethinkdb:
        build:
            context: ./rethinkdb
        volumes:
            - ./data/rethinkdb:/data
        expose:
            - "28015"
            - "29015"
        ports:
            - "28080:8080"
